// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsofluWMRXlC49CNwMCF70BF_arKklQjY',
    appId: '1:109948281340:web:1745481bc058ed636ed279',
    messagingSenderId: '109948281340',
    projectId: 'thirty-seven-hours',
    authDomain: 'thirty-seven-hours.firebaseapp.com',
    storageBucket: 'thirty-seven-hours.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNC8DEEAezPFdG8HNw9QxXVo9Lliyp0Ro',
    appId: '1:109948281340:android:f3d742c31e543f0f6ed279',
    messagingSenderId: '109948281340',
    projectId: 'thirty-seven-hours',
    storageBucket: 'thirty-seven-hours.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWTKkrMhcynAyAyEtZkxzZf1yHiZRJ_s',
    appId: '1:109948281340:ios:a37025ba2ac294b86ed279',
    messagingSenderId: '109948281340',
    projectId: 'thirty-seven-hours',
    storageBucket: 'thirty-seven-hours.appspot.com',
    iosClientId: '109948281340-mglfhhcld22i9i5sqp3u3q6qvrtgdonj.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirtySevenHours',
  );
}
